FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    lightgbm pandas numpy scipy aiohttp pyarrow

WORKDIR /app
COPY retrainer/retrain.py /app/retrain.py

CMD ["python", "/app/retrain.py"]
